version: "3.9"

services:
  finance-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-container
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
	    - NEXT_PUBLIC_DOMAIN_NAME=${NEXT_PUBLIC_DOMAIN_NAME}
      - NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE=${NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WORKSPACE_API_URL=${NEXT_PUBLIC_WORKSPACE_API_URL}
      - HETZNER_S3_REGION=${HETZNER_S3_REGION}
      - NEXT_PUBLIC_HETZNER_S3_ENDPOINT=${NEXT_PUBLIC_HETZNER_S3_ENDPOINT}
      - HETZNER_S3_ACCESS_KEY_ID=${HETZNER_S3_ACCESS_KEY_ID}
      - HETZNER_S3_SECRET_ACCESS_KEY=${HETZNER_S3_SECRET_ACCESS_KEY}
      - NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME=${NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME}
    command: ["bun", "run", "start"]
