import { env } from "@/schemas/env";

export const configs = {
	REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE:
		env.NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE,
	DOMAIN_NAME: env.NEXT_PUBLIC_DOMAIN_NAME,
	SITE_URL: env.NEXT_PUBLIC_SITE_URL,
	API_URL: env.NEXT_PUBLIC_API_URL,
};
