import z from "zod";

const envSchema = z.object({
	NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE: z.string().url(),
	NEXT_PUBLIC_DOMAIN_NAME: z.string(),
	NEXT_PUBLIC_SITE_URL: z.string().url(),
	NEXT_PUBLIC_API_URL: z.string().url(),
	NEXT_PUBLIC_WORKSPACE_API_URL: z.string().url(),
	HETZNER_S3_REGION: z.string(),
	NEXT_PUBLIC_HETZNER_S3_ENDPOINT: z.string().url(),
	HETZNER_S3_ACCESS_KEY_ID: z.string(),
	HETZNER_S3_SECRET_ACCESS_KEY: z.string(),
	NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME: z.string(),
});

export const env = envSchema.parse({
	NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE:
		process.env.NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE,
	NEXT_PUBLIC_DOMAIN_NAME: process.env.NEXT_PUBLIC_DOMAIN_NAME,
	NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
	NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
	NEXT_PUBLIC_WORKSPACE_API_URL: process.env.NEXT_PUBLIC_WORKSPACE_API_URL,
	HETZNER_S3_REGION: process.env.HETZNER_S3_REGION,
	NEXT_PUBLIC_HETZNER_S3_ENDPOINT: process.env.NEXT_PUBLIC_HETZNER_S3_ENDPOINT,
	HETZNER_S3_ACCESS_KEY_ID: process.env.HETZNER_S3_ACCESS_KEY_ID,
	HETZNER_S3_SECRET_ACCESS_KEY: process.env.HETZNER_S3_SECRET_ACCESS_KEY,
	NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME:
		process.env.NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME,
});
