name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy_dev:
    name: Deploy Application in develop environment
    runs-on: develop
    environment: env

    steps:
      - name: Clean .next directory
        run: |
          rm -rf $GITHUB_WORKSPACE/.next

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          echo "NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE=${{ secrets.NEXT_PUBLIC_REDIRECT_WHEN_NOT_AUTHENTICATED_ROUTE }}" >> .env
          echo "NEXT_PUBLIC_DOMAIN_NAME=${{ secrets.NEXT_PUBLIC_DOMAIN_NAME }}" >> .env
          echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_WORKSPACE_API_URL=${{ secrets.NEXT_PUBLIC_WORKSPACE_API_URL }}" >> .env
          echo "HETZNER_S3_REGION=${{ secrets.HETZNER_S3_REGION }}" >> .env
          echo "NEXT_PUBLIC_HETZNER_S3_ENDPOINT=${{ secrets.NEXT_PUBLIC_HETZNER_S3_ENDPOINT }}" >> .env
          echo "HETZNER_S3_ACCESS_KEY_ID=${{ secrets.HETZNER_S3_ACCESS_KEY_ID }}" >> .env
          echo "HETZNER_S3_SECRET_ACCESS_KEY=${{ secrets.HETZNER_S3_SECRET_ACCESS_KEY }}" >> .env
          echo "NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME=${{ secrets.NEXT_PUBLIC_HETZNER_S3_BUCKET_NAME }}" >> .env

      - name: Install Dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 21
          nvm use 21
          npm install bun -g
          bun install

      - name: Deploy Application
        run: |
          docker compose up -d --build

      - name: Clean up old Docker images
        run: |
          docker image prune -a -f
          docker system prune -a --volumes -f
          docker volume prune -f
